function doSomething() {
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
console.log('Data: abcdefghijklmnopqrst');
console.log('Data: ABCDEFGHIJKLMNOPQRST');
}